### ISSUE TITLE
List Customer's Subscriptions isn't working - "error":"Customer not found"

### ISSUE THREAD

**Issue by MrJarnould** [chartmogul/chartmogul-python#44]
I've verified that the provided ChartMogul UUID argument is correct, however, I keep getting a 404 response with the message "Customer not found".  I've tested with both curl and the Python API.

**Comment by pkopac** [comment]
@MrJarnould could you please provide more detail on why you have closed it now? We are interested why that would happen in the first place, if you expected the customer to exist.

**Comment by MrJarnould** [comment]
@pkopac I was using this endpoint `/v1/import/customers/CUSTOMER_UUID/subscriptions` which returned
`{
  "error": "Customer not found"
}`
While `/v1/customers/CUSTOMER_UUID/subscriptions` returns the customer subscription data. 
I still haven't figured out the difference between these two endpoints.

**Comment by pkopac** [comment]
@MrJarnould they are equivalent. They should behave 100 % the same. If you consistently get HTTP 404 on one and HTTP 200 on another, please report it. What I suspect is there were some queues in processing lately (resolved now), so that's why the API might have incorrectly said the customer did not exist (yet).
